# Generated by Django 4.0.3 on 2022-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='USD_CAP',
            field=models.FloatField(null=True),
        ),
    ]
