# Generated by Django 4.0.3 on 2022-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_drug_usd_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='Flag_codes',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
