# Generated by Django 4.0.3 on 2022-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_alter_drug_flag_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='Flag_codes',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
