# Generated by Django 4.0.3 on 2022-03-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_alter_drug_flag_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='drug')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
